# Generated by Django 5.2.7 on 2025-11-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksy_server', '0002_bookannouncement_bookannouncementresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookannouncementresponse',
            name='message',
            field=models.TextField(blank=True, help_text='Mesaj opțional al utilizatorului', null=True),
        ),
    ]
