# Generated by Django 5.2.7 on 2025-11-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksy_server', '0003_bookannouncementresponse_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('returned', 'Returned'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
