# Generated by Django 5.2.7 on 2025-11-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksy_server', '0004_alter_bookrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('NEW_MESSAGE', 'New Message'), ('NEW_REQUEST', 'New Request'), ('REQUEST_ACCEPTED', 'Request Accepted'), ('REQUEST_REJECTED', 'Request Rejected'), ('REQUEST_RETURNED', 'Book Returned'), ('REQUEST_CANCELED', 'Recuest Canceled'), ('FEEDBACK_RECEIVED', 'Feedback Received'), ('NEW_RESPONSE', 'New Response'), ('RESPONSE_ACCEPTED', 'Response Accepted'), ('RESPONSE_REJECTED', 'Response Rejected')], max_length=30),
        ),
    ]
