# Generated by Django 5.2.7 on 2025-12-10 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksy_server', '0006_author_genre_userprofile_rentalhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('action_type', models.CharField(choices=[('messages_sent', 'Messages Sent'), ('books_published', 'Books Published'), ('books_rented', 'Books Rented')], max_length=50)),
                ('threshold', models.PositiveIntegerField()),
                ('is_repeatable', models.BooleanField(default=False)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='medals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medal',
                'verbose_name_plural': 'Medals',
                'ordering': ['threshold'],
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('books_published', models.PositiveIntegerField(default=0)),
                ('books_rented', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Stats',
                'verbose_name_plural': 'Users Stats',
            },
        ),
        migrations.CreateModel(
            name='UserMedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0)),
                ('is_unlocked', models.BooleanField(default=False)),
                ('unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_progress_update', models.DateTimeField(auto_now=True)),
                ('medal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medals', to='booksy_server.medal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_medals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Medal',
                'verbose_name_plural': 'User Medals',
                'unique_together': {('user', 'medal')},
            },
        ),
    ]
