# Generated by Django 5.2.7 on 2025-12-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksy_server', '0007_medal_userstats_usermedal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstats',
            old_name='messages_sent',
            new_name='books_lent',
        ),
        migrations.AlterField(
            model_name='medal',
            name='action_type',
            field=models.CharField(choices=[('books_published', 'Books Published'), ('books_rented', 'Books Rented'), ('books_lent', 'Books Lent')], max_length=50),
        ),
    ]
