# Generated by Django 5.2.7 on 2026-01-08 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksy_server', '0009_quizquestion_quizansweroption'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quiz_recommended_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_recommendations', to='booksy_server.book'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='quiz_result_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_results', to='booksy_server.genre'),
        ),
    ]
