# Generated by Django 5.2.7 on 2026-01-08 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksy_server', '0010_userprofile_quiz_recommended_book_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteraryDNA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksy_server.genre')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dna', to='booksy_server.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'genre')},
            },
        ),
    ]
